### ISSUE TITLE
About Individual Interaction Description

### ISSUE THREAD

**Issue by Evm7** [liangxuy/Inter-X#12]
Hi! First of all congrats on the amazing dataset and works! This is really promising.

I find your annotations to be well-thought-out, particularly in regard to the big five. However, I wonder if you have thought about providing a description of what each person individually does rather than a single description of the whole interaction.

For instance in the HHI "G001T000A000R000", the text description is :

> The first person walks up to the second person and gives him/her a hug around the shoulders, while the second person puts his/her arms around the first person's waist. Then the first person pats the second person softly on his/her back with his/her right hand.

1. Does "first person" refers always to P1 and "second person" refers to P2? Or is there any way to align an individual description to an individual motion?

The goal would be to have something like:
P1: I walk up to the other person and give him/her a hug around the shoulder. Then I pat the other one softly on his/her back with my right hand.
P2: I put my arms around the other person's waist.

**Comment by liangxuy** [comment]
Hi, sorry for the late reply. We only provide the single description for the whole interaction and we cannot guarantee the alignment between the "first person" and P1. It is interesting but we have not yet provided separate descriptions for each individual.
