### ISSUE TITLE
SMPL version of the dataset

### ISSUE THREAD

**Issue by XueYing126** [liangxuy/Inter-X#13]
Hi,

Thank you for sharing the great work!

I was wondering if you also provide an SMPL version of the dataset? If so, could you please point me to where I can find it?

Thank you!

**Comment by liangxuy** [comment]
Hi, sorry but we only provide the SMPL-X parameters and the skeleton information. The SMPL version is not provided. Maybe you can use [this code](https://github.com/vchoutas/smplx/tree/main/transfer_model) to convert to SMPL parameters.

**Comment by XueYing126** [comment]
Thank you!
