### ISSUE TITLE
Where is environment.yml

### ISSUE THREAD

**Issue by shuowang666** [liangxuy/Inter-X#14]
I cannot find environment.yml while creating the environment.

**Comment by liangxuy** [comment]
Sorry for that. The environment.yml is provided. The training/evaluation code and checkpoints are also released today. Feel free to contact me if you encounter some problems.

**Comment by shuowang666** [comment]
![image](https://github.com/user-attachments/assets/82037107-f54d-47cd-a242-47f3838da59e)
Thank you for your code!  Why are the codes in these two parts the same?

**Comment by liangxuy** [comment]
It should be: 
```
python train_comp_v6.py --name Comp_v6_KLD01 --gpu_id 0 --lambda_kld 0.01 --dataset_name hhi
```

**Comment by shuowang666** [comment]
Thanks very much for your help! 
Will the intergen method be open sourced for the text-to-motion task? Due to the urgency of my recent research, could you please provide the first version of InterGen code by email? I would appreciate it!

**Comment by liangxuy** [comment]
OK, I am glad to help.
