### ISSUE TITLE
Clarification on "train.h5" File

### ISSUE THREAD

**Issue by jzc6915** [liangxuy/Inter-X#15]
Hi,

I noticed that the instructions mention downloading a "train.h5" file, but the files available for download are "inter-x-001.h5" and "train-002.h5." Should I merge these two files to create "train.h5," or is there another file I should be using?

Thank you for your guidance.

Best regards

**Comment by liangxuy** [comment]
I think there might be something wrong with your download. The filename is inter-x.h5 and train.h5/test.h5/val.h5.

![image](https://github.com/user-attachments/assets/bbf4e771-5566-418f-9d7c-ecc0b45c3d69)
![image](https://github.com/user-attachments/assets/88b2fcae-0350-4543-81f8-16b5cb1b37e5)

**Comment by jzc6915** [comment]
Alright, I found the file. It seems there was an issue when downloading everything together, but downloading it separately worked, and I was able to find it. Thank you!
