### ISSUE TITLE
想问下关于Inter-X数据集的标签问题

### ISSUE THREAD

**Issue by junwenxiong** [liangxuy/Inter-X#16]
作者，您好

这个工作感觉很棒，但我有点不明白的地方，想问下几个问题

1.  OptiTrack MoCap system会捕获人体的skeleton信息，为啥还要用SMPL-X模型呀？是为了更精确的3D人体参数吗？
2. SMPL-X模型需要进行训练，是因为该模型难以泛化到新的数据集上吗？如果没有MoCap系统采集的人体skeleton信息，是不是就难以获取到3D人体参数了？

谢谢！

**Comment by liangxuy** [comment]
你好呀，

1. MoCap的默认格式是skeleton信息，但由于SMPL-X是应用范围很广的表征，已经被广泛接受和认可，为了兼容已有的动作数据集，扩大数据集可用性，所以我们额外拟合了SMPL-X参数；
2. SMPL-X只是一种人体动作表征方式，采用skeleton或者SMPL-X本质上没有差别，与泛化性无关。我们采用MoCap，是因为比从视频中提取3D人体参数更精确。也有很多其他工作利用多视角RGB相机来获取3D人体参数，例如BEHAVE、InterGen等，也出现了一些很鲁邦的商用基于RGB相机的动捕系统。

**Comment by junwenxiong** [comment]
谢谢作者回复！
我还有两个问题想问下，
1.对于SMPL-X参数来说，是不是只能通过skeleton信息来拟合？有没有直接输入图片进行拟合SMPL-X参数的模型呀？
2. 如果我想自己收集人体数据集，也需要先提取skeleton信息，再拟合SMPL-X参数，对吗？

**Comment by liangxuy** [comment]
你好，

1. 从单张图片或者视频里可以直接提取SMPL-X参数，学术术语叫human mesh recovery (HMR)，例如[PyMAF-X](https://github.com/HongwenZhang/PyMAF-X), [OSX](https://github.com/IDEA-Research/OSX), [WHAM](https://github.com/yohanshin/WHAM)等很多优秀的工作；
2. 可以参考InterGen的方式，用多视角RGB相机拍摄，然后利用算法提取人体动作，直接得到SMPL-X参数；也可以参考我们工作的方式，用光学动捕/惯性动不做来获取人体动作，但是需要做一步skeleton->SMPL-X的转换。

**Comment by junwenxiong** [comment]
学习了，非常感谢

**Comment by laubravo** [comment]
Hi, great work! A quick question for understanding your collection process better, your mocap system uses infrared cameras and there's no available additional RGB images from the collection process right?

**Comment by liangxuy** [comment]
Yes, we cannot provide RGB images.
