### ISSUE TITLE
About big five personality trait

### ISSUE THREAD

**Issue by jeongeun980906** [liangxuy/Inter-X#5]
Hi. Thank you for releasing the dataset. 

I am curious about the notation of the big five personality trait file. 
It is [118x5], with 59 groups. What is the order of this array? Is it like  [P1,P2,P1,P2,...] or [P1,P1,...,P2,P2,...]?

**Comment by liangxuy** [comment]
It's like [P1,P2,P1,P2,...].

**Comment by jeongeun980906** [comment]
Thank you so much!
