### ISSUE TITLE
 About text-conditioned interaction generation on the Inter-X dataset

### ISSUE THREAD

**Issue by MichaelaQ** [liangxuy/Inter-X#8]
Hello，thank you for your amazing work！
Now I want to run Inter-X dataset on MDM，but I have a problem about txt file.
The txt files for HumanML3D that has processed sentence ,like #a/DET man/NOUN kick/VERB something/PRON or/CCONJ someone/PRON with/ADP his/DET left/ADJ leg/NOUN#0.0#0.0
But Inter-X txt files just have  original description.If I want to use this dataset,how can I process them?
Thank you!

**Comment by liangxuy** [comment]
Hi, I will release the preprocessing code within these days. You can also refer to the original code of [text_process.py](https://github.com/EricGuo5513/HumanML3D/blob/main/text_process.py).

**Comment by MichaelaQ** [comment]
Thank  you!
