### ISSUE TITLE
About interaction_order.pkl

### ISSUE THREAD

**Issue by JackYu6** [liangxuy/Inter-X#9]
Great work！
I have some confusion about the numbers in interaction_order.pkl. 
In README.md you say: 0 means P1 is actor; 1 means P2 is actor. But when I use the visualization program you provided to visualize the motion (P1 is the blue one while P2 is the orange one), I find it seems that the order is opposite to what you described. So I'm wondering whether I have misunderstood?
Thanks.

**Comment by liangxuy** [comment]
Hi, thank you for pointing out this. I double-checked the visualization results and found that **"0 means P2 (orange one) is actor; 1 means P1 (blue one) is actor"**.

**Comment by JackYu6** [comment]
Thank you for your prompt reply.
Best.

**Comment by Silverster98** [comment]
Could you update the README? Plenty of time and computation are wasted due to the wrong README.

@liangxuy
